import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],
    theme: {
        extend: {
            colors: {
                'primary':                    '#173809',
                'on-primary':                 '#ffffff',
                'primary-container':          '#2d4f1e',
                'on-primary-container':       '#98c083',
                'primary-fixed':              '#c5efad',
                'primary-fixed-dim':          '#a9d293',
                'on-primary-fixed':           '#062100',
                'on-primary-fixed-variant':   '#2d4f1e',
                'secondary':                  '#77574d',
                'on-secondary':               '#ffffff',
                'secondary-container':        '#fed3c7',
                'on-secondary-container':     '#795950',
                'secondary-fixed':            '#ffdbd0',
                'secondary-fixed-dim':        '#e7bdb1',
                'on-secondary-fixed':         '#2c160e',
                'on-secondary-fixed-variant': '#5d4037',
                'tertiary':                   '#422c0a',
                'on-tertiary':                '#ffffff',
                'tertiary-container':         '#5b421e',
                'on-tertiary-container':      '#d2af82',
                'tertiary-fixed':             '#ffddb3',
                'tertiary-fixed-dim':         '#e5c192',
                'on-tertiary-fixed':          '#291800',
                'on-tertiary-fixed-variant':  '#5b421f',
                'surface':                    '#fcf9f4',
                'surface-dim':                '#dcdad5',
                'surface-bright':             '#fcf9f4',
                'surface-container-lowest':   '#ffffff',
                'surface-container-low':      '#f6f3ee',
                'surface-container':          '#f0ede8',
                'surface-container-high':     '#ebe8e3',
                'surface-container-highest':  '#e5e2dd',
                'surface-variant':            '#e5e2dd',
                'surface-tint':               '#446733',
                'on-surface':                 '#1c1c19',
                'on-surface-variant':         '#43493e',
                'outline':                    '#73796d',
                'outline-variant':            '#c3c8bb',
                'inverse-surface':            '#31302d',
                'inverse-on-surface':         '#f3f0eb',
                'inverse-primary':            '#a9d293',
                'error':                      '#ba1a1a',
                'on-error':                   '#ffffff',
                'error-container':            '#ffdad6',
                'on-error-container':         '#93000a',
                'background':                 '#fcf9f4',
                'on-background':              '#1c1c19',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg:      '0.25rem',
                xl:      '0.5rem',
                full:    '0.75rem',
            },
            fontFamily: {
                headline: ['Newsreader', 'serif'],
                body:     ['Manrope', 'sans-serif'],
                label:    ['Manrope', 'sans-serif'],
                serif:    ['Newsreader', 'serif'],
                sans:     ['Manrope', ...defaultTheme.fontFamily.sans],
            },
        },
    },
    plugins: [forms],
};
